### ISSUE TITLE
SQL文件可以发一下吗

### ISSUE THREAD

**Issue by Jesse54211** [cdq1712446949/blog#2]
SQL文件可以发一下吗

**Comment by cdq1712446949** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jesse54211"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月5日(星期天) 下午2:57
收件人:&nbsp;"cdq1712446949/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cdq1712446949/blog] SQL文件可以发一下吗 (#2)





 
SQL文件可以发一下吗

**Comment by Jesse54211** [comment]
可以发一下吗

**Comment by cdq1712446949** [comment]
刚才发的附件就是，你仔细看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jesse54211"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 下午3:07
收件人: "cdq1712446949/blog"<blog@noreply.github.com&gt;; 
抄送: "ヅてＤＱ"<1712446949@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [cdq1712446949/blog] SQL文件可以发一下吗 (#2)





 
可以发一下吗

**Comment by Jesse54211** [comment]
邮件好像有乱码哎 没有sql的附件  如果方便的话你能发一份到542119880@qq.com邮箱吗？万分感谢

**Comment by YaoJG-543** [comment]
可以发一下sql文件吗？1954792710@qq.com

**Comment by Jesse54211** [comment]
ok
